config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence:true
  validates :body, presence:true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
# 直す
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      flash.now[:alert] = 'alert'
      @books = Book.all
      render :index
    end
  end
  
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
   
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = 'Book was successfully destroyed.'
    redirect_to '/books'
  end
 
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class="form-box">
  <h1>Editing Book</h1>
  
  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <!--バリデーションエラー-->
  <% if @book.errors.any? %>
  <div class="error-message">
    <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  
  <div class="title-box">
    <h4 class="title-form">Title</h4>
    <%= f.text_field :title %>
  </div>
  
  <div class="body-box">
    <h4>Body</h4>
    <%= f.text_area :body %>
  </div>
  
  <div class="submit">
    <%= f.submit 'Update Book' %>
  </div>
  
  <% end %>
</div>

<div class="action">
  <%= link_to'Show', book_path(@book.id) %> | <%= link_to'Back',  '/books' %>
</div>

app/views/books/index.html.erb
<!--フラッシュメッセージ-->
<% if flash[:notice] %>
  <div class="notice" role="notice">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<h1 class="heading">Books</h1>

<table>
  
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to 'Show', "/books/#{book.id}" %></td>
    <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
    <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
</table>

 <h2 class="heading">New Book</h2>
 
 
  <div class="form-box">
  <%= form_with model: @book do |f| %>
  
  <!--バリデーションエラー-->
    <% if @book.errors.any? %>
    <div class="error-message">
      <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="title-box">
      <h4 class="title-form">Title</h4>
      <%= f.text_field:title %>
    </div>
    <div class="body-box">
      <h4 class="body-form">Body</h4>
      <%= f.text_area:body %>
    </div>
    <div class="submit">
      <%= f.submit'Create Book' %>
    </div>
  <% end %>
  </div>
  
 

app/views/books/new.html.erb
<div class="form-box">
  <h2 class="heading">New Book</h2>
  
  <%= form_with model: @book do |f| %>
  <div class="title-box">
    <h4 class="title-form">Title</h4>
    <%= f.text_field:title %>
  </div>
  <div class="body-box">
    <h4 class="body-form">Body</h4>
    <%= f.text_area:body %>
  </div>
  <div class="submit">
    <%= f.submit'Create Book' %>
  </div>
  
  <% end %>

</div>

app/views/books/show.html.erb
<!--フラッシュメッセージ-->
<% if flash[:notice] %>
  <div class="notice" role="notice">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>


<p><strong>Title:</strong><%= @book.title %></p>

<p><strong>Body:</strong><%= @book.body %></p>

<%= link_to'Edit', edit_book_path(@book.id) %> | <%= link_to'Back', '/books' %>

app/views/homes/top.html.erb
<body>
  <h1>ようこそ <strong>Bookers</strong> へ !</h1>
  
  <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>

  <p><%= link_to "start", '/books' %></p>
  
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>